### ISSUE TITLE
latitude_of_origin should determine projection.center, not projection.rotate.

### ISSUE THREAD

**Issue by mbostock** [veltman/d3-stateplane#1]
It looks like the d3.geoConicConformal projections are mapping the latitude_of_origin parameter to rotation in phi. But, the phi rotation should be zero for these projections—the latitude_of_origin just executes a simple vertical shift rather than a spherical rotation, and this is unnecessary with d3-geo since the expectation is that you’re going to use *projection*.fitSize or *projection*.fitExtent anyway. However, if you wanted to, perhaps the most idiomatic approach would be to replace it with *projection*.center. So for example, this:

```js
d3.geoConicConformal()
    .parallels([34 + 56 / 60, 36 + 14 / 60])
    .rotate([92, -34 - 20 / 60])
```

Becomes this:

```js
d3.geoConicConformal()
    .parallels([34 + 56 / 60, 36 + 14 / 60])
    .rotate([92, 0])
    .center([0, 34 - 20 / 60])
```

https://gis.stackexchange.com/questions/112252/whats-the-purpose-of-the-reference-latitude-in-lambert-conformal-conic

**Comment by mbostock** [comment]
Before:

<img width="680" alt="48-before" src="https://cloud.githubusercontent.com/assets/230541/20274070/430d1740-aa48-11e6-8115-9d6d6e35c4bf.png">

After:

<img width="680" alt="48-after" src="https://cloud.githubusercontent.com/assets/230541/20274075/490f994c-aa48-11e6-9bbd-94b59b87a6fe.png">

**Comment by veltman** [comment]
Apologies, I somehow missed this - thanks for the detailed report!
