### ISSUE TITLE
typo in readme: missing closing "]" for a few examples in the readme

### ISSUE THREAD

**Issue by sebastian-ch** [veltman/d3-stateplane#2]
hello! 

I noticed that a few examples in the README are missing the closing "]" in the ```.rotate()``` method.

for example: 
### NAD83 / Virginia North (EPSG:32146)

```js
var projection = d3.geoConicConformal()
  .parallels([38 + 2 / 60, 39 + 12 / 60])
  .rotate([78 + 30 / 60, 0);
```

should be: 

### NAD83 / Virginia North (EPSG:32146)

```js
var projection = d3.geoConicConformal()
  .parallels([38 + 2 / 60, 39 + 12 / 60])
  .rotate([78 + 30 / 60, 0]);
```

**Comment by veltman** [comment]
Oops, sorry - I somehow didn't get notified of this! It's resolved.
